package cc.creativecomputing.gl4;

import com.jogamp.opengl.GL4;

public enum GLPrimitiveType {
	POINTS(GL4.GL_POINTS),
	LINE_STRIP(GL4.GL_LINE_STRIP),
	LINE_LOOP(GL4.GL_LINE_LOOP),
	LINES(GL4.GL_LINES),
	TRIANGLE_STRIP(GL4.GL_TRIANGLE_STRIP),
	TRIANGLE_FAN(GL4.GL_TRIANGLE_FAN),
	TRIANGLES(GL4.GL_TRIANGLES),
	LINES_ADJACENCY(GL4.GL_LINES_ADJACENCY),
	LINE_STRIP_ADJACENCY(GL4.GL_LINE_STRIP_ADJACENCY),
	TRIANGLES_ADJACENCY(GL4.GL_TRIANGLES_ADJACENCY),
	TRIANGLE_STRIP_ADJACENCY(GL4.GL_TRIANGLE_STRIP_ADJACENCY),
	PATCHES(GL4.GL_PATCHES);
	
	private int _myGLID;
	
	GLPrimitiveType(int theGLID){
		_myGLID = theGLID;
	}
	
	public int glID(){
		return _myGLID;
	}
	
	public static GLPrimitiveType fromGLID(int theGLID){
		switch(theGLID){
		case GL4.GL_POINTS:return POINTS;
		case GL4.GL_LINE_STRIP:return LINE_STRIP;
		case GL4.GL_LINE_LOOP:return LINE_LOOP;
		case GL4.GL_LINES:return LINES;
		case GL4.GL_TRIANGLE_STRIP:return TRIANGLE_STRIP;
		case GL4.GL_TRIANGLE_FAN:return TRIANGLE_FAN;
		case GL4.GL_TRIANGLES:return TRIANGLES;
		case GL4.GL_LINES_ADJACENCY:return LINES_ADJACENCY;
		case GL4.GL_LINE_STRIP_ADJACENCY:return LINE_STRIP_ADJACENCY;
		case GL4.GL_TRIANGLES_ADJACENCY:return TRIANGLES_ADJACENCY;
		case GL4.GL_TRIANGLE_STRIP_ADJACENCY:return TRIANGLE_STRIP_ADJACENCY;
		case GL4.GL_PATCHES:return PATCHES;
		}
		return null;
	}
}

