package cc.creativecomputing.gl.enums;

import com.jogamp.opengl.GL4;

public enum GLDebugOutputType {
	DEBUG_TYPE_ERROR(GL4.GL_DEBUG_TYPE_ERROR),
	DEBUG_TYPE_DEPRECATED_BEHAVIOR(GL4.GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR),
	DEBUG_TYPE_UNDEFINED_BEHAVIOR(GL4.GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR),
	DEBUG_TYPE_PORTABILITY(GL4.GL_DEBUG_TYPE_PORTABILITY),
	DEBUG_TYPE_PERFORMANCE(GL4.GL_DEBUG_TYPE_PERFORMANCE),
	DEBUG_TYPE_MARKER(GL4.GL_DEBUG_TYPE_MARKER),
	DEBUG_TYPE_PUSH_GROUP(GL4.GL_DEBUG_TYPE_PUSH_GROUP),
	DEBUG_TYPE_POP_GROUP(GL4.GL_DEBUG_TYPE_POP_GROUP),
	DEBUG_TYPE_OTHER(GL4.GL_DEBUG_TYPE_OTHER),
	DONT_CARE(GL4.GL_DONT_CARE);
	
	private int _myGLID;
	
	GLDebugOutputType(int theGLID){
		_myGLID = theGLID;
	}
	
	public int glID(){
		return _myGLID;
	}
	
	public static GLDebugOutputType fromGLID(int theGLID){
		switch(theGLID){
		case GL4.GL_DEBUG_TYPE_ERROR:return DEBUG_TYPE_ERROR;
		case GL4.GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR:return DEBUG_TYPE_DEPRECATED_BEHAVIOR;
		case GL4.GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR:return DEBUG_TYPE_UNDEFINED_BEHAVIOR;
		case GL4.GL_DEBUG_TYPE_PORTABILITY:return DEBUG_TYPE_PORTABILITY;
		case GL4.GL_DEBUG_TYPE_PERFORMANCE:return DEBUG_TYPE_PERFORMANCE;
		case GL4.GL_DEBUG_TYPE_MARKER:return DEBUG_TYPE_MARKER;
		case GL4.GL_DEBUG_TYPE_PUSH_GROUP:return DEBUG_TYPE_PUSH_GROUP;
		case GL4.GL_DEBUG_TYPE_POP_GROUP:return DEBUG_TYPE_POP_GROUP;
		case GL4.GL_DEBUG_TYPE_OTHER:return DEBUG_TYPE_OTHER;
		case GL4.GL_DONT_CARE:return DONT_CARE;
		}
		return null;
	}
}

