package cc.creativecomputing.gl.enums;

import com.jogamp.opengl.GL4;

public enum GLErrorCode {
	NO_ERROR(GL4.GL_NO_ERROR),
	OUT_OF_MEMORY(GL4.GL_OUT_OF_MEMORY),
	INVALID_ENUM(GL4.GL_INVALID_ENUM),
	INVALID_VALUE(GL4.GL_INVALID_VALUE),
	INVALID_OPERATION(GL4.GL_INVALID_OPERATION),
	INVALID_FRAMEBUFFER_OPERATION(GL4.GL_INVALID_FRAMEBUFFER_OPERATION),
	STACK_OVERFLOW(GL4.GL_STACK_OVERFLOW),
	STACK_UNDERFLOW(GL4.GL_STACK_UNDERFLOW);
	
	private int _myGLID;
	
	private GLErrorCode(int theGLID){
		_myGLID = theGLID;
	}
	
	public int glID(){
		return _myGLID;
	}
	
	public static GLErrorCode fromGLID(int theGLID){
		switch(theGLID){
		case GL4.GL_NO_ERROR:return NO_ERROR;
		case GL4.GL_OUT_OF_MEMORY:return OUT_OF_MEMORY;
		case GL4.GL_INVALID_ENUM:return INVALID_ENUM;
		case GL4.GL_INVALID_VALUE:return INVALID_VALUE;
		case GL4.GL_INVALID_OPERATION:return INVALID_OPERATION;
		case GL4.GL_INVALID_FRAMEBUFFER_OPERATION:return INVALID_FRAMEBUFFER_OPERATION;
		case GL4.GL_STACK_OVERFLOW:return STACK_OVERFLOW;
		case GL4.GL_STACK_UNDERFLOW:return STACK_UNDERFLOW;
		}
		return null;
	}
}

