package cc.creativecomputing.gl.enums;

import com.jogamp.opengl.GL4;

public enum GLPixelStorageMode {
	PACK_SWAP_BYTES(GL4.GL_PACK_SWAP_BYTES),
	PACK_LSB_FIRST(GL4.GL_PACK_LSB_FIRST),
	PACK_ROW_LENGTH(GL4.GL_PACK_ROW_LENGTH),
	PACK_SKIP_ROWS(GL4.GL_PACK_SKIP_ROWS),
	PACK_SKIP_PIXELS(GL4.GL_PACK_SKIP_PIXELS),
	PACK_ALIGNMENT(GL4.GL_PACK_ALIGNMENT),
	PACK_IMAGE_HEIGHT(GL4.GL_PACK_IMAGE_HEIGHT),
	PACK_SKIP_IMAGES(GL4.GL_PACK_SKIP_IMAGES),
	PACK_COMPRESSED_BLOCK_WIDTH(GL4.GL_PACK_COMPRESSED_BLOCK_WIDTH),
	PACK_COMPRESSED_BLOCK_HEIGHT(GL4.GL_PACK_COMPRESSED_BLOCK_HEIGHT),
	PACK_COMPRESSED_BLOCK_DEPTH(GL4.GL_PACK_COMPRESSED_BLOCK_DEPTH),
	PACK_COMPRESSED_BLOCK_SIZE(GL4.GL_PACK_COMPRESSED_BLOCK_SIZE),
	UNPACK_SWAP_BYTES(GL4.GL_UNPACK_SWAP_BYTES),
	UNPACK_LSB_FIRST(GL4.GL_UNPACK_LSB_FIRST),
	UNPACK_ROW_LENGTH(GL4.GL_UNPACK_ROW_LENGTH),
	UNPACK_SKIP_ROWS(GL4.GL_UNPACK_SKIP_ROWS),
	UNPACK_SKIP_PIXELS(GL4.GL_UNPACK_SKIP_PIXELS),
	UNPACK_ALIGNMENT(GL4.GL_UNPACK_ALIGNMENT),
	UNPACK_IMAGE_HEIGHT(GL4.GL_UNPACK_IMAGE_HEIGHT),
	UNPACK_SKIP_IMAGES(GL4.GL_UNPACK_SKIP_IMAGES),
	UNPACK_COMPRESSED_BLOCK_WIDTH(GL4.GL_UNPACK_COMPRESSED_BLOCK_WIDTH),
	UNPACK_COMPRESSED_BLOCK_HEIGHT(GL4.GL_UNPACK_COMPRESSED_BLOCK_HEIGHT),
	UNPACK_COMPRESSED_BLOCK_DEPTH(GL4.GL_UNPACK_COMPRESSED_BLOCK_DEPTH),
	UNPACK_COMPRESSED_BLOCK_SIZE(GL4.GL_UNPACK_COMPRESSED_BLOCK_SIZE);
	
	private int _myGLID;
	
	private GLPixelStorageMode(int theGLID){
		_myGLID = theGLID;
	}
	
	public int glID(){
		return _myGLID;
	}
	
	public static GLPixelStorageMode fromGLID(int theGLID){
		switch(theGLID){
		case GL4.GL_PACK_SWAP_BYTES:return PACK_SWAP_BYTES;
		case GL4.GL_PACK_LSB_FIRST:return PACK_LSB_FIRST;
		case GL4.GL_PACK_ROW_LENGTH:return PACK_ROW_LENGTH;
		case GL4.GL_PACK_SKIP_ROWS:return PACK_SKIP_ROWS;
		case GL4.GL_PACK_SKIP_PIXELS:return PACK_SKIP_PIXELS;
		case GL4.GL_PACK_ALIGNMENT:return PACK_ALIGNMENT;
		case GL4.GL_PACK_IMAGE_HEIGHT:return PACK_IMAGE_HEIGHT;
		case GL4.GL_PACK_SKIP_IMAGES:return PACK_SKIP_IMAGES;
		case GL4.GL_PACK_COMPRESSED_BLOCK_WIDTH:return PACK_COMPRESSED_BLOCK_WIDTH;
		case GL4.GL_PACK_COMPRESSED_BLOCK_HEIGHT:return PACK_COMPRESSED_BLOCK_HEIGHT;
		case GL4.GL_PACK_COMPRESSED_BLOCK_DEPTH:return PACK_COMPRESSED_BLOCK_DEPTH;
		case GL4.GL_PACK_COMPRESSED_BLOCK_SIZE:return PACK_COMPRESSED_BLOCK_SIZE;
		case GL4.GL_UNPACK_SWAP_BYTES:return UNPACK_SWAP_BYTES;
		case GL4.GL_UNPACK_LSB_FIRST:return UNPACK_LSB_FIRST;
		case GL4.GL_UNPACK_ROW_LENGTH:return UNPACK_ROW_LENGTH;
		case GL4.GL_UNPACK_SKIP_ROWS:return UNPACK_SKIP_ROWS;
		case GL4.GL_UNPACK_SKIP_PIXELS:return UNPACK_SKIP_PIXELS;
		case GL4.GL_UNPACK_ALIGNMENT:return UNPACK_ALIGNMENT;
		case GL4.GL_UNPACK_IMAGE_HEIGHT:return UNPACK_IMAGE_HEIGHT;
		case GL4.GL_UNPACK_SKIP_IMAGES:return UNPACK_SKIP_IMAGES;
		case GL4.GL_UNPACK_COMPRESSED_BLOCK_WIDTH:return UNPACK_COMPRESSED_BLOCK_WIDTH;
		case GL4.GL_UNPACK_COMPRESSED_BLOCK_HEIGHT:return UNPACK_COMPRESSED_BLOCK_HEIGHT;
		case GL4.GL_UNPACK_COMPRESSED_BLOCK_DEPTH:return UNPACK_COMPRESSED_BLOCK_DEPTH;
		case GL4.GL_UNPACK_COMPRESSED_BLOCK_SIZE:return UNPACK_COMPRESSED_BLOCK_SIZE;
		}
		return null;
	}
}

