package cc.creativecomputing.gl.enums;

import com.jogamp.opengl.GL4;

public enum GLProgramPipelineStage {
	VERTEX_SHADER_BIT(GL4.GL_VERTEX_SHADER_BIT),
	TESS_CONTROL_SHADER_BIT(GL4.GL_TESS_CONTROL_SHADER_BIT),
	TESS_EVALUATION_SHADER_BIT(GL4.GL_TESS_EVALUATION_SHADER_BIT),
	GEOMETRY_SHADER_BIT(GL4.GL_GEOMETRY_SHADER_BIT),
	FRAGMENT_SHADER_BIT(GL4.GL_FRAGMENT_SHADER_BIT),
	COMPUTE_SHADER_BIT(GL4.GL_COMPUTE_SHADER_BIT),
	ALL_SHADER_BITS((int)GL4.GL_ALL_SHADER_BITS);
	
	private int _myGLID;
	
	private GLProgramPipelineStage(int theGLID){
		_myGLID = theGLID;
	}
	
	public int glID(){
		return _myGLID;
	}
	
	public static GLProgramPipelineStage fromGLID(int theGLID){
		switch(theGLID){
		case GL4.GL_VERTEX_SHADER_BIT:return VERTEX_SHADER_BIT;
		case GL4.GL_TESS_CONTROL_SHADER_BIT:return TESS_CONTROL_SHADER_BIT;
		case GL4.GL_TESS_EVALUATION_SHADER_BIT:return TESS_EVALUATION_SHADER_BIT;
		case GL4.GL_GEOMETRY_SHADER_BIT:return GEOMETRY_SHADER_BIT;
		case GL4.GL_FRAGMENT_SHADER_BIT:return FRAGMENT_SHADER_BIT;
		case GL4.GL_COMPUTE_SHADER_BIT:return COMPUTE_SHADER_BIT;
		case (int)GL4.GL_ALL_SHADER_BITS:return ALL_SHADER_BITS;
		}
		return null;
	}
}

