package cc.creativecomputing.gl.enums;

import com.jogamp.opengl.GL4;

public enum GLQueryTarget {
	TIME_ELAPSED(GL4.GL_TIME_ELAPSED),
	TIMESTAMP(GL4.GL_TIMESTAMP),
	SAMPLES_PASSED(GL4.GL_SAMPLES_PASSED),
	ANY_SAMPLES_PASSED(GL4.GL_ANY_SAMPLES_PASSED),
	PRIMITIVES_GENERATED(GL4.GL_PRIMITIVES_GENERATED),
	TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN(GL4.GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN);
	
	private int _myGLID;
	
	private GLQueryTarget(int theGLID){
		_myGLID = theGLID;
	}
	
	public int glID(){
		return _myGLID;
	}
	
	public static GLQueryTarget fromGLID(int theGLID){
		switch(theGLID){
		case GL4.GL_TIME_ELAPSED:return TIME_ELAPSED;
		case GL4.GL_TIMESTAMP:return TIMESTAMP;
		case GL4.GL_SAMPLES_PASSED:return SAMPLES_PASSED;
		case GL4.GL_ANY_SAMPLES_PASSED:return ANY_SAMPLES_PASSED;
		case GL4.GL_PRIMITIVES_GENERATED:return PRIMITIVES_GENERATED;
		case GL4.GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN:return TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN;
		}
		return null;
	}
}

