package cc.creativecomputing.kle.motors;

public enum CCMotorSetupTypes {
	SETUP_1_MOTOR_1_CONNECTION,
	SETUP_2_MOTOR_1_CONNECTION,
	SETUP_2_MOTOR_2_CONNECTION,
	SETUP_2_MOTOR_2_CONNECTION_LINEAR,
	SETUP_2_MOTOR_ROTATION_AXIS,
	SETUP_1_MOTOR_ROTATION,
}
